### ISSUE TITLE
Class 'Postal\Parser' not found

### ISSUE THREAD

**Issue by joebeaver89** [openvenues/php-postal#24]
I have installed libpostal and php postal. I've followed the steps detailed in the readme but can't get the PHP bindings to work at all, I get message that the class is not found.

My PHP version is 7.2.24. My phpinfo() displays that postal is enabled:
![image](https://user-images.githubusercontent.com/2727898/74254905-0698f580-4ce9-11ea-9b76-523ea40437d7.png)

When I use php on the command line with `php -a` I paste the code you have in the readme `$parsed = Postal\Parser::parse_address("The Book Club 100-106 Leonard St, Shoreditch, London, Greater London, EC2A 4RH, United Kingdom");` but get the message:

`Uncaught Error: Class 'Postal\Parser' not found in php shell code:1`

I get the same result trying to use the same in a script. Have I done something wrong along the way?

**Comment by joebeaver89** [comment]
Never mind, I'm an idiot :)

**Comment by arya6000** [comment]
@joebeaver89 facing the same issue. What was the solution?

**Comment by joebeaver89** [comment]
> @joebeaver89 facing the same issue. What was the solution?

PHP on the command line uses a separate php.ini file so you need to enable the extension in that one too.
